language: csharp
mono: none
dist: xenial
dotnet: 2.2.300
branches:
  only:
  - master
  - /^release\/.*$/
script:
  - dotnet restore
  - dotnet tool install coveralls.net --version 1.0.0 --tool-path tools
  - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
  - ./tools/csmacnz.coveralls --opencover -i ./src/Kaffee.Tests/coverage.opencover.xml --useRelativePaths