language: csharp
solution: kaffee-api.sln
install:
  - nuget restore kaffee-api.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release kaffee-api.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./src/Kaffee.Tests/bin/Release/Kaffee.Tests.dll