version: '2'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - 'mongo:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret

volumes:
  mysql_database:
  mongo:
