version: '2'
services:
  kaffee:
    build: .
    ports:
      - 5000:80
    depends_on: 
      - mongo
    environment: 
      KaffeeDatabaseSettings__ConnectionString: ${MONGO_CONNECTION_STRING}
      WeatherService__DarkSkySettings__Token: ${DARK_SKY_TOKEN}
      SecurityKey: ${SECURITY_KEY}
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - 'mongo:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret

volumes:
  mysql_database:
  mongo:
